const express = require('express')
const router = express.Router()
const { google } = require('googleapis')
const { oauth2Client } = require('../auth')

router.post('/email-test', async (req, res) => {
	const { userEmail, pdfBase64 } = req.body

	if (!userEmail || !pdfBase64) {
		return res.status(400).json({ success: false, error: 'Missing userEmail or pdfBase64' })
	}

	const base64Data = pdfBase64.replace(/^data:application\/pdf;base64,/, '')
	const sender = process.env.GMAIL_SENDER

	// Build raw RFC 2822 MIME message with PDF attachment
	const boundary = 'debate_boundary_' + Date.now()
	const mime = [
		`From: ${sender}`,
		`To: ${userEmail}`,
		`Subject: Debate Session Report by Debate Coach`,
		'MIME-Version: 1.0',
		`Content-Type: multipart/mixed; boundary="${boundary}"`,
		'',
		`--${boundary}`,
		'Content-Type: text/plain; charset="UTF-8"',
		'',
		'Hi,\n\nThank you for completing your debate session with Debate Coach.\n\nYour session report is attached to this email as a PDF.\nIt includes your overall score, dimension breakdown, and\npersonalized feedback based on your performance.\n\nReview it to see where you did well and what to\nfocus on next time.\n\n---\nThis is an automated report generated by Debate Coach.\nPlease do not reply to this email.',
		'',
		`--${boundary}`,
		'Content-Type: application/pdf; name="debate-report.pdf"',
		'Content-Transfer-Encoding: base64',
		'Content-Disposition: attachment; filename="debate-report.pdf"',
		'',
		base64Data,
		'',
		`--${boundary}--`,
	].join('\r\n')

	// Base64url encode (Gmail API requirement)
	const raw = Buffer.from(mime).toString('base64')
		.replace(/\+/g, '-')
		.replace(/\//g, '_')
		.replace(/=+$/, '')

	try {
		const gmail = google.gmail({ version: 'v1', auth: oauth2Client })
		await gmail.users.messages.send({
			userId: 'me',
			requestBody: { raw },
		})
		console.log('[EMAIL] Sent to', userEmail)
		res.json({ success: true })
	} catch (error) {
		console.error('[EMAIL ERROR]', error.message)
		res.status(500).json({ success: false, error: error.message })
	}
})

module.exports = router
